### ISSUE TITLE
JAVA_HOME  is not set

### ISSUE THREAD

**Issue by ziedbouf** [saravanan30erd/opendistro_standalone_installation#4]
https://github.com/saravanan30erd/opendistro_standalone_installation/blob/8774d941bcbeb2fb6611af2bcbab73cc37dcb862/roles/centos7/elasticsearch_opendistro/tasks/opendistro_security.yml#L55

for some reasons during the certificates generation the toolchain start throwing an issue related to the non existence of `JAVA_HOME`. Still exploring the best way to setup `JAVA_HOME` variables during the execution flow.

**Comment by saravanan30erd** [comment]
Please ensure the JAVA is installed in your machine where you are running the ansible playbook. Actually the certificates generation tasks will run in local (ansible) machine.
