### ISSUE TITLE
Instalation issue (elasti- name)

### ISSUE THREAD

**Issue by ibouchakour** [saravanan30erd/opendistro_standalone_installation#8]
Hi, 
Trying to deploy 3 node elastic cluster 

```
es1 ansible_host=myip1 ip=myip1 roles=data,master
es2 ansible_host=myip2 ip=myip2 roles=data,master
es3 ansible_host=myip3 ip=myip3 roles=data,ingest

kibana1 ansible_host=myip1 ip=myip1

# List all the nodes in the ES cluster
[es-cluster]
es1
es2
es3

# List all the Master eligible nodes under this group
[master]
es1
es2

[kibana]
kibana1

```
Got this issue while trying to install it 
The error appears to be in '~/opendistro_standalone_installation-master1/roles/centos7/elasticsearch_opendistro/tasks/main.yml': line 3, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

tasks file for elasti- name: include java.yml
- hostname:
^ here

any solution ? 
Thanks

**Comment by saravanan30erd** [comment]
@ibouchakour Sorry, its syntax mistake. It should have added mistakenly after I did the test.

Please check it and let me know.
